include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
    - lib/l10n/**
    - lib/debug/**

  errors:
    # حوّل هذه إلى Errors بحيث تفشل التحليلات/الهوكس إذا وُجدت
    use_build_context_synchronously: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: warning

linter:
  rules:
    # قواعد عامة
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    unnecessary_this: true

    # حساسة لواجهات Flutter
    use_build_context_synchronously: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    avoid_catches_without_on_clauses: true
    avoid_dynamic_calls: true

    # شكل الكود/السلامة
    always_put_control_body_on_new_line: true
    curly_braces_in_flow_control_structures: true
