workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    working_directory: apps/wawapp_client
    scripts:
      - name: Guard secrets
        script: |
          cd ../..
          pwsh -File tools/guards/guard-secrets.ps1
      - name: Get dependencies
        script: flutter pub get
      - name: Generate l10n
        script: flutter gen-l10n
      - name: Build debug APK
        script: flutter build apk --debug --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk