workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    working_directory: apps/wawapp_client
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Generate l10n
        script: flutter gen-l10n
      - name: Build debug APK
        script: flutter build apk --debug --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    ios_release:
    name: iOS Release IPA
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - appstore_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.wawapp.client
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'ios-v*'
          include: true
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    working_directory: apps/wawapp_client
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Generate l10n
        script: flutter gen-l10n
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build IPA for App Store
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
