// Mocks generated by Mockito 5.4.6 from annotations
// in wawapp_client/test/providers/profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:core_shared/core_shared.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wawapp_client/features/profile/data/client_profile_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ClientProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockClientProfileRepository extends _i1.Mock
    implements _i2.ClientProfileRepository {
  MockClientProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.ClientProfile?> watchProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchProfile,
          [userId],
        ),
        returnValue: _i3.Stream<_i4.ClientProfile?>.empty(),
      ) as _i3.Stream<_i4.ClientProfile?>);

  @override
  _i3.Future<_i4.ClientProfile?> getProfile(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [userId],
        ),
        returnValue: _i3.Future<_i4.ClientProfile?>.value(),
      ) as _i3.Future<_i4.ClientProfile?>);

  @override
  _i3.Future<void> createProfile(_i4.ClientProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile(_i4.ClientProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePhotoUrl(
    String? userId,
    String? photoUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhotoUrl,
          [
            userId,
            photoUrl,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.SavedLocation>> watchSavedLocations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchSavedLocations,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.SavedLocation>>.empty(),
      ) as _i3.Stream<List<_i4.SavedLocation>>);

  @override
  _i3.Future<List<_i4.SavedLocation>> getSavedLocations(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedLocations,
          [userId],
        ),
        returnValue:
            _i3.Future<List<_i4.SavedLocation>>.value(<_i4.SavedLocation>[]),
      ) as _i3.Future<List<_i4.SavedLocation>>);

  @override
  _i3.Future<void> addSavedLocation(
    String? userId,
    _i4.SavedLocation? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addSavedLocation,
          [
            userId,
            location,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateSavedLocation(
    String? userId,
    _i4.SavedLocation? location,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSavedLocation,
          [
            userId,
            location,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSavedLocation(
    String? userId,
    String? locationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSavedLocation,
          [
            userId,
            locationId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
