// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDejGR0uiXzdhbb_zN1wk3KDaxsQdfjzMk',
    appId: '1:363341993641:web:617f5384a6162a8b683bb8',
    messagingSenderId: '363341993641',
    projectId: 'wawapp-952d6',
    authDomain: 'wawapp-952d6.firebaseapp.com',
    storageBucket: 'wawapp-952d6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBloqHWTJ5N5HaoWwxymrr34ZmgRrzvPGA',
    appId: '1:363341993641:android:344b79d7b86a067d683bb8',
    messagingSenderId: '363341993641',
    projectId: 'wawapp-952d6',
    storageBucket: 'wawapp-952d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgebmhbF3bm3CaJOr5RBbbI0bfe1Cxy9Q',
    appId: '1:363341993641:ios:2f5a5d64f06d6b8f683bb8',
    messagingSenderId: '363341993641',
    projectId: 'wawapp-952d6',
    storageBucket: 'wawapp-952d6.firebasestorage.app',
    iosBundleId: 'com.wawapp.admin',
  );
}
